-- CreateTable
CREATE TABLE "AnalisisFacial" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "userId" INTEGER NOT NULL,
    "idioma" TEXT,
    "formaDeOjos" TEXT,
    "formaDelrostro" TEXT,
    "tipoDePiel" TEXT,
    "simetriaFacial" TEXT,
    "colorPrincipalPielHex" TEXT,
    "subtonosPiel" TEXT,
    "frenteHex" TEXT,
    "mejillasHex" TEXT,
    "narizHex" TEXT,
    "mentonHex" TEXT,
    "colorOjosHex" TEXT,
    "anilloLimbalColorHex" TEXT,
    "anilloLimbalGrosor" TEXT,
    "contrasteEsclerotica" TEXT,
    "proporcionOjosCara" TEXT,
    "distanciaInterocular" TEXT,
    "formaDeLaNariz" TEXT,
    "anchoDeLasFosas" TEXT,
    "formaDeLosLabios" TEXT,
    "contornoDeLabios" TEXT,
    "tamanoDeLaBoca" TEXT,
    "colorBaseHex" TEXT,
    "reflejosTonos" TEXT,
    "reflejosProporcion" TEXT,
    "raizHex" TEXT,
    "puntasHex" TEXT,
    "coloresQueFavorecen" JSONB,
    "coloresQueDesfavorecen" JSONB,
    "estacionDeColor" TEXT,
    CONSTRAINT "AnalisisFacial_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
